### ISSUE TITLE
[Feature request] Lista softwares utili 

### ISSUE THREAD

**Issue by Torkin1** [f-dinucci/materiale-ingegneria-free#1]
Ciao, innanzitutto complimenti per l'iniziativa!

Ho pensato che tra il materiale utile che il sito può offrire potrebbe andare bene una lista di softwares utili per accompagna lo studio delle materie ingegneristiche, evidenziando in quali aspetti essi portano vantaggi rispetto ad altri.

Personalmente, ne conosco molti che riguardano il CdL di Ingegneria Informatica, ma anche alcuni relativi allo studio in generale (creazione di mappe concettuali, appunti elettronici a mano libera, ...) e di simulazione e calcolo matematico (Processing, ...).

**Comment by f-dinucci** [comment]
Grazie, in effetti sarebbe utile, potresti iniziare ad elencare i software cui hai accennato?

**Comment by Torkin1** [comment]
Questa potrebbe essere una prima bozza
[engineerToolbox.md](https://github.com/f-dinucci/materiale-ingegneria-free/files/6465845/engineerToolbox.md)

**Comment by f-dinucci** [comment]
Abbiamo riorganizzato la struttura del sito in modo da avere anche una sezione software, appena possibile iniziamo a compilarla

**Comment by f-dinucci** [comment]
> Questa potrebbe essere una prima bozza
> [engineerToolbox.md](https://github.com/f-dinucci/materiale-ingegneria-free/files/6465845/engineerToolbox.md)

L'abbiamo integrata [nella sezione dedicata ai software](https://f-dinucci.github.io/materiale-ingegneria-free/Software/Software). Al momento non abbiamo ancora inserito i plugin (dobbiamo vedere un attimo come organizzarli) ed i servizi solamente online (non sappiamo ancora se includerli o meno)

Nel caso ti venissero in mente altri suggerimenti siamo qui, basta una issue o una pull request ;)
